yiisoft/arrays

src/ArrayHelper.php
| Tests pass?   | -
| Fixed issues  | -
=> fix `ArrayHelper::merge`

src/ArrayHelper.php, tests/ArrayHelperTest.php
=> Fixed merging of integer keyed arrays with same value.

src/ArrayHelper.php, tests/ArrayHelperTest.php
| Fixed issues  | #20 
1. Fixed Issue #20 
2. Some improvement after recursive calling `static::getValue`
3. Made new feature: at now possible to combine arrays/object as value
=> Object compatible

src/ArrayHelper.php, src/Modifier/ModifierInterface.php, src/Modifier/RemoveKeys.php, src/Modifier/ReplaceValue.php, src/Modifier/UnsetValue.php, tests/ArrayHelperTest.php
=> Add array modifiers

src/ArrayHelper.php, tests/ArrayHelperTest.php
This PR is related to the Issue #9
=> Clean up mess in ArrayHelper::multisort() #9

src/Modifier/ReverseValues.php, tests/ArrayHelperTest.php
=> added ReverseValues modifier

src/ArrayHelper.php
According to changes in `yiisoft/strings` package.
=> Fix use of `StringHelper::htmlspecialchars`

src/ArrayHelper.php, tests/ArrayHelper/RemoveTest.php, tests/ArrayHelperTest.php
| Is bugfix?    |  ❌
| Fixed issues  | #3
=> Add method removeByPath() and support keys as arrays in method remove()

src/ArrayHelper.php, tests/ArrayAccessTraitTest.php, tests/ArrayHelper/ArrayHelperTest.php, tests/ArrayHelper/GetValueTest.php, tests/ArrayHelper/MergeTest.php, tests/ArrayHelper/SetValueTest.php, tests/ArrayableTraitTest.php, tests/Objects/ArrayAccessObject.php, tests/Objects/HardArrayableObject.php, tests/Objects/Magic.php, tests/Objects/NestedStaticObject.php, tests/Objects/ObjectWithNestedArrayableObject.php, tests/Objects/Post1.php, tests/Objects/Post2.php, tests/Objects/Post3.php, tests/Objects/SimpleArrayableObject.php, tests/Objects/StaticObject.php
- Add more tests for `ArrayHelper::setValue`
- Fix phpdoc
- Change test files location more understandable
=> Enhancements

psalm.xml, src/ArrayHelper.php, src/ArraySorter.php, src/Modifier/InsertValueBeforeKey.php, src/Modifier/ModifierInterface.php, src/Modifier/ReplaceValue.php, tests/ArrayHelper/ApplyModifiersTest.php, tests/ArrayHelper/IndexTest.php
=> Add psalm annotations

README.md, src/ArrayHelper.php, tests/ArrayHelper/ArrayHelperTest.php, tests/ArrayHelper/KeyAndPathExistsTest.php
=> Add ArrayHelper::pathExists

CHANGELOG.md, README.md, src/ArrayHelper.php, tests/ArrayHelper/GroupTest.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Added an alias for indexing by groups

.styleci.yml, CHANGELOG.md, src/ArrayHelper.php, src/ArraySorter.php, tests/ArrayHelper/RemoveTest.php, tests/Objects/ArrayAccessObject.php, tests/Objects/HardArrayableObject.php, tests/Objects/NestedStaticObject.php, tests/Objects/SimpleArrayableObject.php, tests/Objects/StaticObject.php
| Breaks BC?    | ✔️
| Fixed issues  | -
=> Finalize classes

src/ArrayAccessTrait.php
=> Fix mutation tests for PHP 8.1

src/ArrayHelper.php
| Fixed issues  | #107 - related
A small improvement to avoid confusion.
=> (Docs) Improve description for ArrayHelper::getObjectVars()

.styleci.yml, tests/ArrayHelper/ToArrayTest.php, tests/Objects/Magic.php
=> Update StyleCI config

.github/workflows/rector.yml, psalm.xml, rector.php, tests/ArrayHelper/GetValueTest.php, tests/ArrayHelper/SetValueTest.php
=> Improve psalm and rector configs + Minor tests improvements

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/bc.yml, .github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml, .github/workflows/rector.yml, .github/workflows/static.yml, README.md, composer.json, rector.php, src/ArrayHelper.php
=> Fix psalm errors + Improve CI + Cleanup

CHANGELOG.md, README.md, src/ArrayHelper.php, tests/ArrayHelper/RenameKeyTest.php, tests/ArrayHelper/ReplaceKeyTest.php
=> Add `ArrayrHelper::renameKey()`

CHANGELOG.md, src/ArrayAccessTrait.php, src/ArrayHelper.php, src/ArraySorter.php, src/ArrayableTrait.php, tests/ArrayHelper/RenameKeyTest.php
=> Minor refactor

CHANGELOG.md, composer.json, psalm.xml, src/ArrayAccessTrait.php, src/ArrayHelper.php, src/ArrayableInterface.php, src/ArrayableTrait.php, src/PsalmTraitHelper.php
=> Improve psalm types

psalm.xml, psalm80.xml, tests/PsalmTraitHelper.php
=> Improve psalm analysis

CHANGELOG.md, composer.json, tests/ArrayHelper/GetValueByPathTest.php, tests/ArrayHelper/GetValueTest.php, tools/composer-require-checker/composer.json
=> Bump `yiisoft/strings` + More tests
